# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install pipenv
      run: |
        pip install pipenv
    - name: Install dependencies
      run: |
        mkdir .venv
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
       make check
