# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python # Set Python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install pipenv
      run: |
        pip install pipenv
    - name: Install dependencies
      run: |
        mkdir .venv
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
       make check
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: .pytest_cache/pytest.json
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
